### ISSUE TITLE
Value search functions

### ISSUE THREAD

**Issue by mwhall** [mwhall/QUOREM#28]
A function for each of the relevant Models that searches through its attached objects and upstream tree to see if it can find a connected value.

e.g., Result.search_parameter("storage_temperature") will search backwards to see if it can identify one (or a set) of "storage_temperature" values in its linked features, samples, their steps, processes, etc. "storage_temperature" should be tied to Samples, perhaps upstream from the Samples used in this Result, so we have to go upstream from the Samples attached to the Result.

Some heuristics are required to short-circuit the search without doing too much searching. A downstream_of() function could be a helpful shortcut.

**Comment by alexmanuele** [comment]
flagged "done: awaiting testing" in light of current value table functions; v1.x can build on what exists but waht's in place may be sufficient to close V1 issue

**Comment by mwhall** [comment]
This is covered by a variety of new helper functions, including get_parameters, get_values, and queryset_to_table.
