### ISSUE TITLE
CSV/Pandas Data Download/Export

### ISSUE THREAD

**Issue by mwhall** [mwhall/QUOREM#30]
We require an export functionality to get data out to users.

To maximize the utility, we should write a function to export specific queries to Pandas dataframes (which can then be accessed programmatically, for things like reports and other displays), and then .to_csv() can be called to prepare it for the user to download.

There should be one export url that accepts query parameters which define the table that is being exported. Effectively, we want a nice clean API for as many generic export queries as possible, that will merge all the requested data appropriately. Then we can add convenience functions to the Models for single- and multi-object queries, and use those to generate and display download links on the appropriate pages.

**Comment by alexmanuele** [comment]
Perhaps 'django-import-export' could be helpful for this.
https://django-import-export.readthedocs.io/en/latest/getting_started.html

**Comment by mwhall** [comment]
That one looks useful. I think I even had it in the requirements at some point. Or maybe we should just leapfrog all that and work on integrating https://github.com/wq/django-data-wizard
